#!/usr/bin/env python
import socket
import sys
#!/usr/bin/env python
import librunner as uphone
BQ = uphone.device() # runner daemon sur le BQ
BQ.ip('192.168.1.67',5656)
BQ.connect()
BQ.send('ls -a')
BQ.close()